// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳 每50秒发送一次
type S2C_Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_Pong) Reset() {
	*x = S2C_Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Pong) ProtoMessage() {}

func (x *S2C_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Pong.ProtoReflect.Descriptor instead.
func (*S2C_Pong) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{0}
}

type C2S_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_Ping) Reset() {
	*x = C2S_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Ping) ProtoMessage() {}

func (x *C2S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Ping.ProtoReflect.Descriptor instead.
func (*C2S_Ping) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{1}
}

// 充值成功
type S2C_Recharge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float64 `protobuf:"fixed64,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *S2C_Recharge) Reset() {
	*x = S2C_Recharge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Recharge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Recharge) ProtoMessage() {}

func (x *S2C_Recharge) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Recharge.ProtoReflect.Descriptor instead.
func (*S2C_Recharge) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_Recharge) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 提现成功
type S2C_Withdrawal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float64 `protobuf:"fixed64,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *S2C_Withdrawal) Reset() {
	*x = S2C_Withdrawal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Withdrawal) ProtoMessage() {}

func (x *S2C_Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Withdrawal.ProtoReflect.Descriptor instead.
func (*S2C_Withdrawal) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_Withdrawal) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 异地登录
type S2C_RemoteLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_RemoteLogin) Reset() {
	*x = S2C_RemoteLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RemoteLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RemoteLogin) ProtoMessage() {}

func (x *S2C_RemoteLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RemoteLogin.ProtoReflect.Descriptor instead.
func (*S2C_RemoteLogin) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{4}
}

// 位置上报
type C2S_OnlineSeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat string `protobuf:"bytes,1,opt,name=Seat,proto3" json:"Seat,omitempty"` //活动位置
}

func (x *C2S_OnlineSeat) Reset() {
	*x = C2S_OnlineSeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_OnlineSeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_OnlineSeat) ProtoMessage() {}

func (x *C2S_OnlineSeat) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_OnlineSeat.ProtoReflect.Descriptor instead.
func (*C2S_OnlineSeat) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_OnlineSeat) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

// 抽取银金钻转盘
type C2S_TreasureRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"` //类型 1silver 2gold 3diamond
}

func (x *C2S_TreasureRun) Reset() {
	*x = C2S_TreasureRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_TreasureRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TreasureRun) ProtoMessage() {}

func (x *C2S_TreasureRun) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TreasureRun.ProtoReflect.Descriptor instead.
func (*C2S_TreasureRun) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_TreasureRun) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type S2C_SpinRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`                     //奖品id
	Amount       float64 `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`            //数额
	CurrencyType int32   `protobuf:"varint,3,opt,name=CurrencyType,proto3" json:"CurrencyType,omitempty"` //货币类型 1cash 2bonus
}

func (x *S2C_SpinRun) Reset() {
	*x = S2C_SpinRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_SpinRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SpinRun) ProtoMessage() {}

func (x *S2C_SpinRun) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SpinRun.ProtoReflect.Descriptor instead.
func (*S2C_SpinRun) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_SpinRun) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *S2C_SpinRun) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *S2C_SpinRun) GetCurrencyType() int32 {
	if x != nil {
		return x.CurrencyType
	}
	return 0
}

type C2S_RaffleRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_RaffleRun) Reset() {
	*x = C2S_RaffleRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RaffleRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RaffleRun) ProtoMessage() {}

func (x *C2S_RaffleRun) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RaffleRun.ProtoReflect.Descriptor instead.
func (*C2S_RaffleRun) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{8}
}

// 公告
type S2C_Notice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"` //内容
}

func (x *S2C_Notice) Reset() {
	*x = S2C_Notice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Notice) ProtoMessage() {}

func (x *S2C_Notice) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Notice.ProtoReflect.Descriptor instead.
func (*S2C_Notice) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_Notice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_cmd_proto protoreflect.FileDescriptor

var file_cmd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x0a, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x0a, 0x0a, 0x08, 0x43,
	0x32, 0x53, 0x5f, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x28, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x32, 0x43,
	0x5f, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x24, 0x0a, 0x0e,
	0x43, 0x32, 0x53, 0x5f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x61, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x65,
	0x61, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x52, 0x75, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x32, 0x43,
	0x5f, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x61, 0x66, 0x66,
	0x6c, 0x65, 0x52, 0x75, 0x6e, 0x22, 0x26, 0x0a, 0x0a, 0x53, 0x32, 0x43, 0x5f, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x5a,
	0x04, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_rawDescOnce sync.Once
	file_cmd_proto_rawDescData = file_cmd_proto_rawDesc
)

func file_cmd_proto_rawDescGZIP() []byte {
	file_cmd_proto_rawDescOnce.Do(func() {
		file_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_rawDescData)
	})
	return file_cmd_proto_rawDescData
}

var file_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cmd_proto_goTypes = []interface{}{
	(*S2C_Pong)(nil),        // 0: pb.S2C_Pong
	(*C2S_Ping)(nil),        // 1: pb.C2S_Ping
	(*S2C_Recharge)(nil),    // 2: pb.S2C_Recharge
	(*S2C_Withdrawal)(nil),  // 3: pb.S2C_Withdrawal
	(*S2C_RemoteLogin)(nil), // 4: pb.S2C_RemoteLogin
	(*C2S_OnlineSeat)(nil),  // 5: pb.C2S_OnlineSeat
	(*C2S_TreasureRun)(nil), // 6: pb.C2S_TreasureRun
	(*S2C_SpinRun)(nil),     // 7: pb.S2C_SpinRun
	(*C2S_RaffleRun)(nil),   // 8: pb.C2S_RaffleRun
	(*S2C_Notice)(nil),      // 9: pb.S2C_Notice
}
var file_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_init() }
func file_cmd_proto_init() {
	if File_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Recharge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Withdrawal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RemoteLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_OnlineSeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_TreasureRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_SpinRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_RaffleRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Notice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_goTypes,
		DependencyIndexes: file_cmd_proto_depIdxs,
		MessageInfos:      file_cmd_proto_msgTypes,
	}.Build()
	File_cmd_proto = out.File
	file_cmd_proto_rawDesc = nil
	file_cmd_proto_goTypes = nil
	file_cmd_proto_depIdxs = nil
}
